inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  SuggestExtensions: false
  NewCops: enable

Style/Documentation:
  Enabled: false
